# Generated by Django 2.2.1 on 2020-06-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing_machine_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WashingMachineSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[('SUNDAY', 'SUNDAY'), ('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATuERDAY', 'SATuERDAY')], max_length=10)),
                ('washing_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washing_machine_bookings', to='slot_booking.WashingMachine')),
            ],
        ),
        migrations.CreateModel(
            name='UserSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('washing_machine_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_booking.WashingMachineSlot')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.IntegerField()),
                ('date', models.DateField()),
                ('request_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=10)),
                ('requested_user_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_booking.UserSlot')),
            ],
        ),
    ]
