# Generated by Django 2.2.1 on 2020-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0002_auto_20200528_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_range', models.IntegerField()),
            ],
        ),
    ]
